version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: backend:${BACKEND_VERSION:-latest}
    restart: always
    ports:
    - "8000:8000"
    volumes:
    - ./:/app/src
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
    environment:
      BACKEND_HOST: 0.0.0.0
      BACKEND_DB_HOST: backend-db
      BACKEND_DB_PORT: 5432
      BACKEND_DB_USER: backend
      BACKEND_DB_PASS: backend
      BACKEND_DB_BASE: backend

  db:
    image: postgres:13
    hostname: backend-db
    environment:
      POSTGRES_PASSWORD: "backend"
      POSTGRES_USER: "backend"
      POSTGRES_DB: "backend"
    volumes:
    - backend-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test:
      - CMD
      - pg_isready
      - -U
      - backend
      interval: 2s
      timeout: 3s
      retries: 40

  pgweb:
    image: sosedoff/pgweb
    restart: always
    ports:
    - "8081:8081"
    environment:
    - DATABASE_URL=postgres://${BACKEND_DB_USER}:${BACKEND_DB_PASS}@db:${BACKEND_DB_PORT}/${BACKEND_DB_BASE}?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"

volumes:
  backend-db-data:
    name: backend-db-data
