"""empty message

Revision ID: de3fc20171cf
Revises: 31323c4d3bcf
Create Date: 2022-06-03 19:13:52.168891

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "de3fc20171cf"
down_revision = "31323c4d3bcf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_superuser", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("is_primary", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_primary")
    op.drop_column("users", "is_superuser")
    # ### end Alembic commands ###
